---
- hosts: localhost
  tasks:
        - name: Install flatpak via dnf
          dnf:
            name: flatpak
            state: latest

        - name: Install Virtual Manager/QEMU/KVM via dnf
          dnf:
            name: virt-install
            state: latest

        - name: Add the flathub flatpak repository remote to the user installation
          flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
            method: system 

        - name: Install PyCharm-Community via dnf 
          dnf:
            name: pycharm-community 
            state: latest

        - name: Install Secrets via flatpak 
          flatpak:
            name: org.gnome.World.Secrets 
            state: present 
            method: system

