---
- hosts: managed_hosts 
  tasks:
        - name: Set timezone to America/Chicago 
          timezone:
            name: America/Chicago

        - name: Set git config 
          copy:
            src: ./main.gitconfig
            dest: ~/.gitconfig
