---
- hosts: localhost
  tasks:
        - name: Install flatpak via dnf
          dnf:
            name: flatpak
            state: latest

        - name: Install Virtual Manager/QEMU/KVM via dnf
          dnf:
            name: virt-install
            state: latest


        - name: Add the flathub flatpak repository remote to the user installation
          flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
            method: system 

        - name: Install PyCharm-Community via flatpak 
          flatpak:
            name: com.jetbrains.PyCharm-Community 
            state: present
            method: system
